### ISSUE TITLE
Context for timer

### ISSUE THREAD

**Issue by uspiritwolf** [Whirlcode/dobirna-gra#41]
**Goal:** Have the ability to control the timer in a complex hierarchy/nesting, where you need to manage the visibility of the timer depending on the game stats and/or the current transition animation.
**Suggestion:** use context, as this allows you to create as many timers as you want independent of each other. The final form is something like:

```
<TimerContext id={`player-card-${id}`} currentTime={} duration={1000} visiable={false/true}>>
.... big nesting
.....
     <TimerView id={`player-card-${id}``}
        ... timer
     </TimerView>
.....
.....
</TimerController>
```

**Objectives:**
- To find out if the use of context is appropriate
- check if changing the context does not lead to re-rendering of all components, but only those that are bound to the context.
- props/cons in comparison using redux/slice

**Comment by xmasterpiecex** [comment]
Okay. I faced a problem while trying figure out useContext approach (Link to the issue : https://github.com/facebook/react/issues/18178#issuecomment-595846312)
So i decided to make this with Redux approach using separate slice for control timer through managing whether animated component on screen or not.
